; Dark theme settings for flat assembler IDE for Windows. Don't forget to set your Include folder path.
[Environment]
Include=
[Compiler]
Memory=65536
Passes=100
Priority=0
[Options]
SecureSelection=0
AutoBrackets=0
AutoIndent=1
SmartTabs=1
OptimalFill=0
ReviveDeadKeys=0
ConsoleCaret=1
TimeScroll=0
[Colors]
Text=255,255,255
Background=0,0,0
SelectionText=255,255,255
SelectionBackground=0,120,215
Symbols=255,0,255
Numbers=0,144,0
Strings=176,0,0
Comments=128,128,128
[Font]
Face=Courier New
Height=16
Width=0
Weight=0
Italic=0
CharSet=1
[Window]
Top=199
Left=233
Right=617
Bottom=523
Maximized=1
[Help]
Path=
